export type Quest = {
  name: string;
  campaign: Faction;
  parts: Part[];
};

export type Faction = "Korolev" | "Osiris" | "ICA";

export type ViewMode = "quest" | "upgrade" | "items";

export type ItemSource = "quest" | "upgrade" | null;

export type Part = {
  dropItems?: ItemHandin[];
  deliverItems?: ItemHandin[];
  description?: string;
  name: PartName;
  requires: PartName | null;
};

export type ItemHandin = {
  item: ItemName;
  quantity: number;
  dropLocation?: DropLocation;
};

export type IconName =
  | "fast_rewind"
  | "remove"
  | "add"
  | "fast_forward"
  | "star"
  | "grade"
  | "done"
  | "visibility"
  | "visibility_off";

type DropLocation =
  | "Swamp Camp"
  | "Gate C"
  | "Main Office"
  | "Comms Tower"
  | "Stockpile"
  | "Pinnacle Lab"
  | "Satellite Dish"
  | "Fulfillment Center"
  | "Nutrion Farms Office"
  | "Waterfall Lab"
  | "Garage Office"
  | "Server Room"
  | "East Collection Point"
  | "Korolev Island HQ"
  | "Korolev Core Outpost"
  | "Osiris Labs"
  | "Osiris Research Center";

export type ItemName =
  | "Nickel"
  | "Compound Sheets"
  | "Hydraulic Piston"
  | "Flawed Veltecite"
  | "Circuit Board"
  | "Altered Nickel"
  | "Cloudy Veltecite"
  | "Ball Bearings"
  | "Titan Ore"
  | "Electronic Cables"
  | "Resin Gun"
  | "Metallic Alloys"
  | "Optic Glass"
  | "Brittle Titan Ore"
  | "Pure Veltecite"
  | "Shard Slicer"
  | "Zero Systems CPU"
  | "Meteor Fragment"
  | "Focus Crystal"
  | "Hardened Bone Plates"
  | "Clear Veltecite"
  | "Radio Equipment"
  | "Pure Focus Crystal"
  | "Spinal Base"
  | "Biological Sampler"
  | "Sample Container"
  | "Valuable Data Drive"
  | "Jewellery"
  | "Restoration Shield (Green)"
  | "Medium Backpack"
  | "Rattler Skin"
  | "Portable Lab"
  | "Toxic Glands"
  | "Marauder Flesh"
  | "Rattler Eyes"
  | "Mature Rattler Eyes"
  | "Strider Flesh"
  | "Unique Data Drive"
  | "Print Resin"
  | "Textiles"
  | "Salvaged Insulation"
  | "Smart Mesh"
  | "Magnetic Field Stabilizer"
  | "Co-TEC MultiTool"
  | "Gyroscope"
  | "Miniature Reactor"
  | "Copper Wire"
  | "Osiris Scrip"
  | "Korolev Scrip"
  | "ICA Scrip"
  | "Veltecite Heart"
  | "Old Currency"
  | "Meteor Core"
  | "Letium"
  | "Hardened Metals"
  | "Azure Tree Bark"
  | "Frag Grenade"
  | "Fusion Cartridge Batteries"
  | "Uncommon Data Drive"
  | "Rare Data Drive"
  | "Smoke Grenade"
  | "Pale Ivy Blossom"
  | "Indigenous Fruit"
  | "Magic-GROW Fertilizer"
  | "Charged Spinal Base"
  | "Polymetallic Prefabricate"
  | "Shock Absorber"
  | "Master Unit CPU"
  | "Interactive Screen"
  | "Oil Tank"
  | "Waterweed Filament"
  | "Brightcap Mushroom"
  | "Weak Medkit"
  | "Medical Supplies"
  | "Blue Runner Egg"
  | "Old Medicine"
  | "Derelict Explosives"
  | "Glowy Brightcap Mushroom"
  | "Dustbloom"
  | "Crusher Flesh"
  | "Crusher Hide"
  | "Elite Crusher Heart"
  | "Heavy Strider Flesh"
  | "Aluminum Scrap"
  | "Savage Marauder Flesh"
  | "Nutritional Bar"
  | "Autoloader"
  | "Kmarks"
  | "Progenitor Composite"
  | "Progenitor Slag"
  | "Spine Briar"
  | "Abyss Alloy"
  | "Tharis Iron"
  | "Pure Tharis Iron"
  | "Tharis Iron Ingot"
  | "Charged Tharis Iron Ingot"
  | "Teratomorphic Crystal Core"
  | "Huge Forged Backpack";

export type ItemRarity =
  | "Common"
  | "Uncommon"
  | "Rare"
  | "Epic"
  | "Exotic"
  | "Legendary";

export type UpgradeTreeName =
  | "Generate Kmarks"
  | "Kmark Passive Cap"
  | "Generate Aurum"
  | "Aurum Passive Cap"
  | "Supply Crate"
  | "Stash"
  | "Safe Pockets"
  | "Workbench"
  | "Quarters";

export type UpgradeLevel = {
  items: ItemHandin[];
  kMarks: number;
};

type Stage = {
  levels: UpgradeLevel[];
};

export type Upgrade = {
  tree: UpgradeTreeName;
  stages: Stage[];
};

export type QuestProgress = Record<string, number>;

export type UpgradeProgress = Record<UpgradeTreeName, Record<number, number>>;

export type PartName = KorolevPartName | IcaPartName | OsirisPartName;

export type KorolevPartName =
  | "Welcome to the Workforce"
  | "Sometimes violence IS the answer"
  | "Spare Parts"
  | "Contaminated Waters"
  | "Company Identity"
  | "Mineral Master"
  | "Inevitable Automation"
  | "Tools of the Trade"
  | "Very Fast Moving Parts"
  | "Final Touches"
  | "Spring Cleaning"
  | "Active Scan"
  | "Through the Optic Glass"
  | "A Titanic Request"
  | "A Heavy Conscience"
  | "A Pinch of Pure Power"
  | "Aggressive Marketing"
  | "Miners' Strike"
  | "Zero Waste"
  | "For all the Trees"
  | "From Above"
  | "Thick Skinned"
  | "Uncharted Territory Part 1"
  | "Uncharted Territory Part 2"
  | "Uncharted Territory Part 3"
  | "Uncharted Territory Part 4"
  | "Clear Focus"
  | "Site Seeing"
  | "Stormbringer"
  | "The Missing Engineer"
  | "Rapid Gentrification"
  | "Supply Drop"
  | "Messenger Service"
  | "Clearing the Way"
  | "Shopping List"
  | "Don't Dig Too Deep"
  | "Just a Call Away"
  | "Collaborative Research"
  | "Lab Heist"
  | "It's All About Branding"
  | "It's in the Blood"
  | "Fresh Meat"
  | "Trek for Data"
  | "In a Deep Dark Hole Part 1"
  | "In a Deep Dark Hole Part 2"
  | "In a Deep Dark Hole Part 3"
  | "In a Deep Dark Hole Part 4"
  | "In a Deep Dark Hole Part 5"
  | "In a Deep Dark Hole Part 6"
  | "In a Deep Dark Hole Part 7"
  | "In a Deep Dark Hole Part 8"
  | "In a Deep Dark Hole Part 9"
  | "In a Deep Dark Hole Part 10"
  | "In a Deep Dark Hole Part 11"
  | "In a Deep Dark Hole Part 12"
  | "In a Deep Dark Hole Part 13"
  | "Building Blocks"
  | "Salvage Ops"
  | "Pattern Testing"
  | "Custom Rig"
  | "Expensive Tastes"
  | "Delicate Parts"
  | "This is Goodbye"
  | "This isn't Science"
  | "Unlimited Power"
  | "The Test Run"
  | "Tough as Nails"
  | "Order Refill"
  | "Exotic Leathers"
  | "Forest Clearing"
  | "Time for More Work? Part 2"
  | "Show Them How It's Done"
  | "A Pick Me Up";

export type IcaPartName =
  | "Simple Needs"
  | "Don't Forget to Recycle"
  | "Animal Control"
  | "Basic Needs"
  | "The Forester"
  | "Audiophiles Beware Part 1"
  | "Audiophiles Beware Part 2"
  | "Audiophiles Beware Part 3"
  | "SOS Sign"
  | "Old Friend"
  | "Doing the Work Part 2"
  | "Doing the Work Part 3"
  | "Doing the Work Part 4"
  | "The Stranded Prospector"
  | "Doing the Work Part 5"
  | "Doing the Work Part 6"
  | "Project Fireball Part 1"
  | "Project Fireball Part 2"
  | "Project Fireball Part 3"
  | "Project Fireball Part 4"
  | "Project Fireball Part 5"
  | "Project Fireball Part 6"
  | "Project Fireball Part 7"
  | "Race to the Bottom Part 1"
  | "Race to the Bottom Part 2"
  | "Race to the Bottom Part 3"
  | "Race to the Bottom Part 4"
  | "Race to the Bottom Part 5"
  | "Race to the Bottom Part 6"
  | "Race to the Bottom Part 7"
  | "Race to the Bottom Part 8"
  | "Race to the Bottom Part 9"
  | "Race to the Bottom Part 10"
  | "Race to the Bottom Part 11"
  | "Race to the Bottom Part 12"
  | "Race to the Bottom Part 13"
  | "Race to the Bottom Part 14"
  | "Race to the Bottom Part 15"
  | "Race to the Bottom Part 16"
  | "Working for the Community Part 1"
  | "Working for the Community Part 2"
  | "Working for the Community Part 3"
  | "Never Give Up Part 1"
  | "Never Give Up Part 2"
  | "Never Give Up Part 3"
  | "Back to Basics? Part 1"
  | "Back to Basics? Part 2"
  | "Back to Basics? Part 3"
  | "Back to Basics? Part 4"
  | "Back to Basics? Part 5"
  | "Back to Basics? Part 6"
  | "Back to Basics? Part 7"
  | "Back to Basics? Part 8"
  | "A Whole New Ecosystem Part 1"
  | "A Whole New Ecosystem Part 2"
  | "A Whole New Ecosystem Part 3"
  | "The Community Needs You Part 1"
  | "The Community Needs You Part 2"
  | "The Community Needs You Part 3"
  | "An Eye for Oil Part 1"
  | "An Eye for Oil Part 2"
  | "Put to the Test Part 1"
  | "Put to the Test Part 2"
  | "Private Business Part 1"
  | "Private Business Part 2"
  | "Private Business Part 3"
  | "Toxic Love Part 1"
  | "Toxic Love Part 2";

export type OsirisPartName =
  | "Prove your Worth"
  | "The Real Wetwork"
  | "Fertile Grounds"
  | "Tick-Tock"
  | "Papers, Please"
  | "Field Research Part 1"
  | "Field Research Part 2"
  | "Old Bones"
  | "Field Research Part 3"
  | "Field Research Part 4"
  | "Field Research Part 5"
  | "Field Research Part 6"
  | "Field Research Part 7"
  | "Extinct Creatures"
  | "Field Research Part 8"
  | "Lost Knowledge Part 1"
  | "Crashed Osiris Freighter"
  | "Lost Knowledge Part 2"
  | "Lost Knowledge Part 3"
  | "The Progenitor Device Part 1"
  | "The Progenitor Device Part 2"
  | "The Progenitor Device Part 3"
  | "The Progenitor Device Part 4"
  | "The Progenitor Device Part 5"
  | "The Progenitor Device Part 6"
  | "The Progenitor Device Part 7"
  | "The Progenitor Device Part 8"
  | "The Progenitor Device Part 9"
  | "The Progenitor Device Part 10"
  | "The Progenitor Device Part 11"
  | "The Progenitor Device Part 12"
  | "The Progenitor Device Part 13"
  | "The Progenitor Device Part 14"
  | "The Progenitor Device Part 15"
  | "The Progenitor Device Part 16"
  | "The Progenitor Device Part 17"
  | "Lost Scientist"
  | "Explosive Delivery Part 1"
  | "Frozen"
  | "Laser Show Part 1"
  | "Laser Show Part 2"
  | "Everything is Crystals Part 1"
  | "Everything is Crystals Part 2"
  | "Everything is Crystals Part 3"
  | "Path to Strong Medkits Part 1"
  | "Path to Strong Medkits Part 2"
  | "Path to Strong Medkits Part 3"
  | "Building a better Death Ray Part 1"
  | "Building a better Death Ray Part 2"
  | "Satellite Master Part 1"
  | "Satellite Master Part 2"
  | "Satellite Master Part 3"
  | "Combat Ready Part 1"
  | "Combat Ready Part 2"
  | "Combat Ready Part 3"
  | "Orbital Repairs Part 1"
  | "Orbital Repairs Part 2"
  | "Orbital Repairs Part 3"
  | "Orbital Repairs Part 4"
  | "Breaking and Entering Part 1"
  | "The Needs of the One Part 1"
  | "The Needs of the One Part 2"
  | "The Needs of the One Part 3"
  | "The Needs of the One Part 4"
  | "Storm Rider Part 1"
  | "Storm Rider Part 2"
  | "Storm Rider Part 3"
  | "Stimulating Developments Part 1"
  | "Stimulating Developments Part 2";

export type QuestPart = {
  questName: string;
  partNumber: number;
};
